inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'pkg/**/*'

Layout/ExtraSpacing:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
