inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'pkg/**/*'

Style/ExtraSpacing:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

SignalException:
  EnforcedStyle: only_raise
